package com.dlya.btbrms.api.drools;

import com.dlya.btbrms.api.drools.BtResourceSet;
import com.dlya.btbrms.api.drools.BtEResourceSetStatus;

rule "Consumo Tasa especial emprendedor"
    salience 3
	dialect "mvel"
	when
        $resSet : BtResourceSet(
            status == BtEResourceSetStatus.INIT && (
                resource["scmod"].value == 108 &&
                resource["sctope"].value  == 2 &&
                resource["aoimp"].value  <= 500
            )
        )
	then
	   $resSet.get("result").setValue("EMP");
	   modify($resSet){
	        setStatus(BtEResourceSetStatus.PROCESSED)
	   }
end

rule "Consumo Tasa especial micro empresa"
    salience 2
	dialect "mvel"
	when
        $resSet : BtResourceSet(
            status == BtEResourceSetStatus.INIT && (
                resource["scmod"].value  == 108 &&
                resource["sctope"].value  == 1 &&
                resource["aoimp"].value  > 500 &&
                resource["aoimp"].value  <= 1000
            )
        )
	then
	    $resSet.get("result").setValue("MICRO");
        modify($resSet){
            setStatus(BtEResourceSetStatus.PROCESSED)
        }
end

rule "Consumo Tasa especial micro empresa sin importe"
    salience 1
	dialect "mvel"
	when
        $resSet : BtResourceSet(
            status == BtEResourceSetStatus.INIT && (
                resource["scmod"].value  == 108 &&
                resource["sctope"].value  == 1
            )
        )
	then
	    $resSet.get("result").setValue("MICRO_NO_IMP");
	    modify($resSet){
	        setStatus(BtEResourceSetStatus.PROCESSED)
	    }
end

