package com.dlya.btbrms.flow.schema;

import com.adelean.inject.resources.junit.jupiter.GivenJsonResource;
import com.adelean.inject.resources.junit.jupiter.TestWithResources;
import com.dlya.btbrms.flow.schema.assign.BtAssignEntry;
import com.dlya.btbrms.flow.schema.assign.BtAssignExpression;
import com.dlya.btbrms.flow.schema.decision.*;
import com.dlya.btbrms.flow.schema.reference.BtReferenceResource;
import com.dlya.btbrms.flow.schema.reference.BtReferenceScalarConst;
import com.dlya.btbrms.flow.schema.step.BtFlowStepAssignment;
import com.dlya.btbrms.flow.schema.step.BtFlowStepDecision;
import com.dlya.btbrms.flow.schema.step.BtFlowStepStart;
import com.dlya.btbrms.flow.schema.types.*;
import com.dlya.btbrms.flow.schema.resouce.BtFlowResource;
import com.dlya.btbrms.flow.schema.resouce.BtFlowResourceConstant;
import com.dlya.btbrms.flow.schema.resouce.BtFlowResourceVariableScalar;
import com.dlya.btbrms.flow.schema.step.BtFlowStep;
import org.assertj.core.api.InstanceOfAssertFactories;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.as;
import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.InstanceOfAssertFactories.*;

@TestWithResources
public class BtFlowParsingTest {
    @GivenJsonResource("/flowJsonSchema/schema_parsing_steps.json")
    BtFlowDefinition schemaSteps;

    @GivenJsonResource("/flowJsonSchema/schema_parsing_resources.json")
    BtFlowDefinition schemaResources;

    @Test
    @DisplayName("JSON flow schema, start")
    public void testStartStep() {
        assertThat(schemaSteps)
                .isNotNull()
                .extracting("flowSteps", as(map(String.class, BtFlowStep.class)))
                .isNotNull()
                .hasSize(3)
                .hasEntrySatisfying("start", start -> assertThat(start)
                        .isNotNull()
                        .asInstanceOf(InstanceOfAssertFactories.type(BtFlowStepStart.class))
                        .hasFieldOrPropertyWithValue("apiName", "start")
                        .hasFieldOrPropertyWithValue("startAt", "assignment1")
                        .hasFieldOrPropertyWithValue("type", BtEFlowStepType.START)
                );
    }

    @Test
    @DisplayName("JSON flow schema, assignment")
    public void testAssignmentStep() {
        assertThat(schemaSteps)
                .isNotNull()
                .extracting("flowSteps", as(map(String.class, BtFlowStep.class)))
                .hasEntrySatisfying("assignment1", start -> assertThat(start)
                        .isNotNull()
                        .asInstanceOf(InstanceOfAssertFactories.type(BtFlowStepAssignment.class))
                        .hasFieldOrPropertyWithValue("apiName", "assignment1")
                        .hasFieldOrPropertyWithValue("label", "Assignment 1")
                        .hasFieldOrPropertyWithValue("next", "decision1")
                        .hasFieldOrPropertyWithValue("description", "Assignment Description 1")
                        .hasFieldOrPropertyWithValue("type", BtEFlowStepType.ASSIGNMENT)
                        .extracting("assignments", as(list(BtAssignEntry.class)))
                        .hasSize(3)
                        .satisfies( array -> assertThat(array)
                            .element(0)
                            .asInstanceOf(InstanceOfAssertFactories.type(BtAssignEntry.class))
                            .satisfies( target -> assertThat(target)
                                    .extracting("target", as(type(BtReferenceResource.class)))
                                    .hasFieldOrPropertyWithValue("apiName", "var1")
                            )
                            .satisfies( source -> assertThat(source)
                                    .extracting("source", as(type(BtReferenceScalarConst.class)))
                                    .hasFieldOrPropertyWithValue("type", BtEReferenceType.CONSTANT)
                                    .hasFieldOrPropertyWithValue("value", "10")
                            )
                        )
                        .satisfies( array -> assertThat(array)
                                .element(1)
                                .asInstanceOf(InstanceOfAssertFactories.type(BtAssignEntry.class))
                                .satisfies( target -> assertThat(target)
                                        .extracting("target", as(type(BtReferenceResource.class)))
                                        .hasFieldOrPropertyWithValue("apiName", "var2")
                                )
                                .satisfies( source -> assertThat(source)
                                        .extracting("source", as(type(BtReferenceResource.class)))
                                        .hasFieldOrPropertyWithValue("type", BtEReferenceType.RESOURCE)
                                        .hasFieldOrPropertyWithValue("apiName", "var3")
                                )
                        )
                        .satisfies( array -> assertThat(array)
                                .element(2)
                                .asInstanceOf(InstanceOfAssertFactories.type(BtAssignEntry.class))
                                .satisfies( target -> assertThat(target)
                                        .extracting("target", as(type(BtReferenceResource.class)))
                                        .hasFieldOrPropertyWithValue("type", BtEReferenceType.RESOURCE)
                                        .hasFieldOrPropertyWithValue("apiName", "var4")
                                )
                                .satisfies( source -> assertThat(source)
                                        .extracting("source", as(type(BtAssignExpression.class)))
                                        .hasFieldOrPropertyWithValue("type", BtEReferenceType.EXPRESSION)
                                        .hasFieldOrPropertyWithValue("expression", "LEN(${var5})")
                                )
                        )
                );

    }

    @Test
    @DisplayName("JSON flow schema, decision")
    public void testDecisionStep() {
        assertThat(schemaSteps)
                .extracting("flowSteps", as(map(String.class, BtFlowStep.class)))
                .hasEntrySatisfying("decision1", start -> assertThat(start)
                        .isNotNull()
                        .asInstanceOf(InstanceOfAssertFactories.type(BtFlowStepDecision.class))
                        .hasFieldOrPropertyWithValue("defaultOutCome", "gxCall1")
                        .hasFieldOrPropertyWithValue("apiName", "decision1")
                        .hasFieldOrPropertyWithValue("label", "decision 1")
                        .hasFieldOrPropertyWithValue("description", "decision Description 1")
                        .hasFieldOrPropertyWithValue("type", BtEFlowStepType.CONDITION)
                        .extracting("outcomes", as(list(BtOutcome.class)))
                        .hasSize(4)
                        .satisfies( array -> assertThat(array)
                                .element(0)
                                .asInstanceOf(InstanceOfAssertFactories.type(BtOutcomeWResources.class))
                                .hasFieldOrPropertyWithValue("type", BtEDecisionOutcomeType.AND)
                                .hasFieldOrPropertyWithValue("outcome", "assign2")
                                .hasFieldOrPropertyWithValue("label", "condition typed AND")
                                .hasFieldOrPropertyWithValue("apiName", "and_outcome")
                                .extracting("entries", as(list(BtOutcomeWResourcesEntry.class)))
                                .hasSize(2)
                                .satisfies( entry -> assertThat(entry)
                                        .element(0)
                                        .asInstanceOf(InstanceOfAssertFactories.type(BtOutcomeWResourcesEntry.class))
                                        .satisfies( target -> assertThat(target)
                                                .extracting("resource", as(type(BtReferenceResource.class)))
                                                .hasFieldOrPropertyWithValue("type", BtEReferenceType.RESOURCE)
                                                .hasFieldOrPropertyWithValue("apiName", "var1")
                                        )
                                        .hasFieldOrPropertyWithValue("operator", BtOperator.EQUALS)
                                        .satisfies( source -> assertThat(source)
                                                .extracting("value", as(type(BtReferenceScalarConst.class)))
                                                .hasFieldOrPropertyWithValue("type", BtEReferenceType.CONSTANT)
                                                .hasFieldOrPropertyWithValue("value", "10")
                                        )
                                )
                                .satisfies( entry -> assertThat(entry)
                                        .element(1)
                                        .asInstanceOf(InstanceOfAssertFactories.type(BtOutcomeWResourcesEntry.class))
                                        .satisfies( target -> assertThat(target)
                                                .extracting("resource", as(type(BtReferenceResource.class)))
                                                .hasFieldOrPropertyWithValue("type", BtEReferenceType.RESOURCE)
                                                .hasFieldOrPropertyWithValue("apiName", "var2")
                                        )
                                        .hasFieldOrPropertyWithValue("operator", BtOperator.EQUALS)
                                        .satisfies( source -> assertThat(source)
                                                .extracting("value", as(type(BtReferenceResource.class)))
                                                .hasFieldOrPropertyWithValue("type", BtEReferenceType.RESOURCE)
                                                .hasFieldOrPropertyWithValue("apiName", "var3")
                                        )
                                )
                        )
                        .satisfies( array -> assertThat(array)
                                .element(1)
                                .asInstanceOf(InstanceOfAssertFactories.type(BtOutcomeWResources.class))
                                .hasFieldOrPropertyWithValue("type", BtEDecisionOutcomeType.OR)
                                .extracting("entries", as(list(BtOutcomeWResourcesEntry.class)))
                                .hasSize(2)
                                .satisfies( entry -> assertThat(entry)
                                        .element(0)
                                        .asInstanceOf(InstanceOfAssertFactories.type(BtOutcomeWResourcesEntry.class))
                                        .satisfies( target -> assertThat(target)
                                                .extracting("resource", as(type(BtReferenceResource.class)))
                                                .hasFieldOrPropertyWithValue("type", BtEReferenceType.RESOURCE)
                                                .hasFieldOrPropertyWithValue("apiName", "var1")
                                        )
                                        .hasFieldOrPropertyWithValue("operator", BtOperator.GREATER_THAN)
                                        .satisfies( source -> assertThat(source)
                                                .extracting("value", as(type(BtReferenceScalarConst.class)))
                                                .hasFieldOrPropertyWithValue("type", BtEReferenceType.CONSTANT)
                                                .hasFieldOrPropertyWithValue("value", "250")
                                        )
                                )
                                .satisfies( entry -> assertThat(entry)
                                        .element(1)
                                        .asInstanceOf(InstanceOfAssertFactories.type(BtOutcomeWResourcesEntry.class))
                                        .satisfies( target -> assertThat(target)
                                                .extracting("resource", as(type(BtReferenceResource.class)))
                                                .hasFieldOrPropertyWithValue("type", BtEReferenceType.RESOURCE)
                                                .hasFieldOrPropertyWithValue("apiName", "var2")
                                        )
                                        .hasFieldOrPropertyWithValue("operator", BtOperator.CONTAINS)
                                        .satisfies( source -> assertThat(source)
                                                .extracting("value", as(type(BtReferenceScalarConst.class)))
                                                .hasFieldOrPropertyWithValue("type", BtEReferenceType.CONSTANT)
                                                .hasFieldOrPropertyWithValue("value", "STR_KEY")
                                        )
                                )
                        )
                        .satisfies( array -> assertThat(array)
                                .element(2)
                                .asInstanceOf(InstanceOfAssertFactories.type(BtOutcomeCustomCondition.class))
                                .hasFieldOrPropertyWithValue("type", BtEDecisionOutcomeType.CUSTOM)
                                .hasFieldOrPropertyWithValue("customCondition", "1 OR 2")
                                .extracting("entries", as(list(BtOutcomeWResourcesEntry.class)))
                                .hasSize(2)
                                .satisfies( entry -> assertThat(entry)
                                        .element(0)
                                        .asInstanceOf(InstanceOfAssertFactories.type(BtOutcomeWResourcesEntry.class))
                                        .satisfies( target -> assertThat(target)
                                                .extracting("resource", as(type(BtReferenceResource.class)))
                                                .hasFieldOrPropertyWithValue("type", BtEReferenceType.RESOURCE)
                                                .hasFieldOrPropertyWithValue("apiName", "var5")
                                        )
                                        .hasFieldOrPropertyWithValue("operator", BtOperator.STARTS_WITH)
                                        .satisfies( source -> assertThat(source)
                                                .extracting("value", as(type(BtReferenceScalarConst.class)))
                                                .hasFieldOrPropertyWithValue("type", BtEReferenceType.CONSTANT)
                                                .hasFieldOrPropertyWithValue("value", "STR_KEY")
                                        )
                                )
                                .satisfies( entry -> assertThat(entry)
                                        .element(1)
                                        .asInstanceOf(InstanceOfAssertFactories.type(BtOutcomeWResourcesEntry.class))
                                        .satisfies( target -> assertThat(target)
                                                .extracting("resource", as(type(BtReferenceResource.class)))
                                                .hasFieldOrPropertyWithValue("type", BtEReferenceType.RESOURCE)
                                                .hasFieldOrPropertyWithValue("apiName", "var2")
                                        )
                                        .hasFieldOrPropertyWithValue("operator", BtOperator.EQUALS)
                                        .satisfies( source -> assertThat(source)
                                                .extracting("value", as(type(BtReferenceResource.class)))
                                                .hasFieldOrPropertyWithValue("type", BtEReferenceType.RESOURCE)
                                                .hasFieldOrPropertyWithValue("apiName", "var3")
                                        )
                                )

                        )
                        .satisfies( array -> assertThat(array)
                                .element(3)
                                .asInstanceOf(InstanceOfAssertFactories.type(BtOutcomeExpression.class))
                                .hasFieldOrPropertyWithValue("type", BtEDecisionOutcomeType.EXPRESSION)
                                .hasFieldOrPropertyWithValue("expression", "OR(AND(EQUALS(v1,v2),EQUALS(v2,v3)),CONTAINS(v4,'_'))")
                        )
                );
    }

    @Test
    @DisplayName("JSON resources")
    public void testResources() {
        assertThat(schemaResources)
                .isNotNull()
                .extracting("flowResources", as(list(BtFlowResource.class)))
                .isNotNull()
                .hasSize(2)
                .element(0)
                .asInstanceOf(InstanceOfAssertFactories.type(BtFlowResourceConstant.class))
                .hasFieldOrPropertyWithValue("apiName", "two")
                .hasFieldOrPropertyWithValue("label", "Two")
                .hasFieldOrPropertyWithValue("description", "Two 2")
                .hasFieldOrPropertyWithValue("resourceType", BtEFlowResourceType.CONSTANT)
                .hasFieldOrPropertyWithValue("dataType", BtEScalarPrimitiveType.NUMBER)
                .satisfies( value -> assertThat(value)
                        .extracting("value", as(type(BtReferenceScalarConst.class)))
                        .hasFieldOrPropertyWithValue("type", BtEReferenceType.CONSTANT)
                        .hasFieldOrPropertyWithValue("value", "2")
                );

        assertThat(schemaResources)
                .extracting("flowResources", as(list(BtFlowResource.class)))
                .element(1)
                .asInstanceOf(InstanceOfAssertFactories.type(BtFlowResourceVariableScalar.class))
                .hasFieldOrPropertyWithValue("apiName", "var1")
                .hasFieldOrPropertyWithValue("label", "variable1")
                .hasFieldOrPropertyWithValue("description", "Description of variable")
                .hasFieldOrPropertyWithValue("resourceType", BtEFlowResourceType.SCALAR_VARIABLE)
                .hasFieldOrPropertyWithValue("dataType", BtEScalarPrimitiveType.TEXT)
                .hasFieldOrPropertyWithValue("in", false)
                .hasFieldOrPropertyWithValue("out", true)
                .hasFieldOrPropertyWithValue("hasDefault", false)
        ;
    }
}